services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: quality
      POSTGRES_PASSWORD: quality
      POSTGRES_DB: data_quality
    ports:
      - "5434:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
  app:
    build: .
    command: uvicorn data_quality_monitoring_platform.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - postgres
  dashboard:
    build: .
    command: streamlit run dashboard/streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    volumes:
      - .:/app
    ports:
      - "8503:8501"
    depends_on:
      - app
